<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Petition extends Model
{
    use HasFactory;

    public $table = 'petitions';

    protected $guarded = ['id'];
    protected $appends = ['outstanding','pdt'];
    protected $hidden = ['updated_at','created_at','stepcnt'];
    protected $casts = [
        'plist' => 'object',
        'verified' => 'object',
        'body' => 'object',
        'routestep' => 'array',
        'rulestep' => 'array',
        'stepcnt' => 'integer',
        'tamt' => 'float',
        'grpstaff'=>'array',
        'needclaim'=>'boolean',
    ];

    public function getRouteKeyName (){
        return 'slug';
//        return parent::getRouteKey(); // TODO: Change the autogenerated stub
    }
    public function ptype(){return $this->belongsTo(Ptype::class);}
    public function stepper(){return $this->belongsTo(Stepper::class,'stepnow','id');}
    public function user(){return $this->belongsTo(User::class,'staff_id','staff_id');}
    public function attachment(){return $this->hasMany(Attachment::class);}
    public function position(){return $this->hasOneThrough(Position::class,Staff::class,'id','id','staff_id','position_id');}
    public function leave(){return $this->hasOneThrough(Leave::class,StaffLeave::class,'id','id','slvid','leaves_id');}
    public function lvtype(){return $this->belongsTo(Leave::class,'typlv','id');}
    public function log(){return $this->hasMany(PetitionLog::class)->with('stepper','staff:fullname');}
    public function logLatest(){return $this->hasOne(PetitionLog::class,'petition_id')->orderByDesc('id');}
    public function attach(){return $this->hasMany(Attachment::class);}
    public function staff(){return $this->belongsTo(Staff::class);}
    public function depart(){return $this->belongsTo(Depart::class);}

    public function setRulestepAttribute($value){$this->attributes['rulestep'] = json_encode($value);}
    public function setRoutestepAttribute($value){$this->attributes['routestep'] = json_encode($value);}
    public function setPlistAttribute($value){$this->attributes['plist'] = $value;}
    public function setPdateAttribute($value){$this->attributes['pdate'] = $value;$this->attributes['pyear'] = date('Y',strtotime($value));}

    public function getRulestepperAttribute(){
        $step = Stepper::with('logLatest')->get();
//        whereIn('id',$this->rulestep)
//        SELECT * FROM mytable WHERE id IN (1,2,3,4) ORDER BY FIELD(id,3,2,1,4);
        $arr = [];
        foreach ($this->rulestep as $s){
            $data = $step->where('id',$s)->first->all();
            $arr[] = $data;
        }
        return $arr;
    }
    public function getRuleCountAttribute(){
        $ar = $this->rulestep;
        if($ar == null) return 0;
        return count($ar);
    }
    public function getRouteCountAttribute(){
        $ar = $this->routestep;
        if($ar == null) return 0;
        return count($ar);
    }
    public function getOutstandingAttribute(){
        $date = Carbon::parse($this->stepdt);
        $now = Carbon::now();
        $diff = $date->diffInDays($now);
        if($this->psts==2 && $diff) return $date->diffForHumans();
        return '';
    }
    public function getPdtAttribute(){return Carbon::parse($this->pdate)->format('d/m/Y');}
    public function getContentAttribute(){
        $cate = (int) $this->attributes['pcate'];
        $body = $this->body;
        $tamt = $this->attributes['tamt'];
        $lv = [];
        if($this->attributes['typlv'] > 0) $lv = $this->lvtype;
        $arr = ['','','',''];

        $amt = number_format($tamt,2);
        if(is_null($body)) return [];
        if ($cate == 1) {
            $arr[0] = date('d M Y', strtotime($this->attributes['pdate']));
            $arr[3] = 'RM '.number_format($this->attributes['tamt'],2);
            return $arr;
        }
        $arr[0] = date('d M Y', strtotime($this->attributes['pdate']));
        if(property_exists($body,'dtout')) $arr[1] = date('d M Y', strtotime($body->dtout));// $this->oContent("Tarikh Keluar", $body->dtout);
        if(property_exists($body,'tout')) $arr[1] = date('h:m A', strtotime($body->tout)); //$this->oContent("Waktu Keluar", Carbon::parse($body->tout)->format('h:i A'));
        if(property_exists($body,'tin')) $arr[2] = date('h:m A', strtotime($body->tin)); //$this->oContent("Waktu Masuk", Carbon::parse($body->tin)->format('h:i A'));
        if(property_exists($body,'dtin')) $arr[2] = date('d M Y', strtotime($body->dtin)); //$this->oContent("Tarikh Kembali", $body->dtin);
        if(property_exists($body,'dtback')) $arr[2] = date('d M Y', strtotime($body->dtback)); //$this->oContent("Tarikh Kembali", $body->dtback);
        if(property_exists($body,'totalamt')) $arr[3] = 'RM '.number_format($body->totalamt,2);//$this->oContent("Jumlah Tuntutan", 'RM '.number_format($body->totalamt,2));
        if(property_exists($body,'num') && $lv) {
            $arr[3] = $lv->typ == 3 ? "RM " . number_format($body->num, 2) : $body->num . " $lv->unit";
        }
        return $arr;
    }
    private function oContent($label,$val){
        return "$label : <span class='text-gray-600 text-hover-primary fw-bold'>$val</span>";
    }
}
