<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
            ['', 'Pembeli Saham dalam Paka Utama Holdings Sdn. Bhd.'],
            ['', 'Kerja-kerja menyiapkan tapak expo berhadapan The Giant , Sungai Petani'],
            ['PTK', 'Bayaran untuk permohonan lesen menduduki sementara (LMS) di atas lot 582 '],
            ['', 'Tuntutan Pengeluaran Rujuk KAHB.(B).2(8)'],
            ['', 'Bayaran Penginapan'],
            ['', 'Bayaran pendahuluan bagi Projek Sangkar Laut Terbuka,Langkawi  & Keli-K'],
            ['PASIR', 'Permohonan lesen kuari pasir'],
            ['', 'Tuntutan bg kerja2 pembangunan ldg hutan tani (getah balak)'],
            ['', 'pendahuluan modal kerja membekal benih cantuman muda'],
            ['', 'Notis 5A'],
            ['', 'Kerja pembangunan Ldg Hutan Tani Kompartment 8, Gng Inas'],
            ['', 'Bayaran kedua - Istana Bukit Malut, Pulau Langkawi'],
            ['', 'Bayaran Permohonan Tanah Binjal lot 1116, kubang pasu'],
            ['', 'Pembaharuan LMS Pulau Ular, Langkawi'],
            ['', 'Lot 87, 89, 1827, 1828, 1783 dan 2098 Bukit Kachi'],
            ['', 'Bayaran permohonan perlombongan bijih besi komp. 4, H.S bukit sungkup'],
            ['', 'Tuntutan hutang Al Farhan ke atas KCE'],
            ['', 'Millage Claim '],
            ['', 'Yuran audit PMBKed bagi tahun berakhir 31/12/2009'],
            ['', 'Cukai HSD 1102, 1103, 1104, 1105, 1106, 1107 & 1109 ulu melaka ,kedawang'],
            ['', 'Petty Cash'],
            ['', 'Cukai HSD 249, Charuk Tawar/Bendang Luas(KUIN)'],
            ['', 'Cukai tanah Bukit Tangga HSD 19890, 19891 dan 19892'],
            ['', 'Cukai HSD 19244, 19245, 19246, 19247&19248 Bukit Kachi'],
            ['', 'Pembaharuan LMS Lot 582, Ulu Mahang, Kulim'],
            ['', 'Premium pasir sungai komp. 10, Hutan Simpan Gunung Bongsu'],
            ['', 'Permohonan permit pasir di Lot 2208 Padang Temak, Daerah Padang Terap'],
            ['', 'Bayaran bagi peralatan dibekal Utas Maju Sdn Bhd'],
            ['', 'Bayaran membangunkan Software Sistem KPW'],
            ['', 'RENTAL /SERVICE- 02/2012'],
            ['', 'ELAUN KERJA LEBIH MASA'],
            ['', 'BAYARAN SMARTPAY'],
            ['', 'Permohonan tanah pasir sungai secara LMS di Kuala Darak, Baling'],
            ['', 'FLIGHT TICKET'],
            ['', 'Bayaran Pendahuluan diri bagi tugasan rasmi.'],
            ['', 'tuntutan elaun perjalanan 02/2012'],
            ['', 'Yuran Setiausaha & Caj utk bulan 01-03/2012 bagi syarikat KCE Sdn.Bhd '],
            ['', 'Sumbangan bagi membina & membaiki struktur binaan'],
            ['', 'Bayaran bil telefon bagi bulan 02/2012-(047318716)'],
            ['', 'Bayaran bil internet 02/2012-(20090420368810)'],
            ['', 'Permohonan permit pengeluaran pasir di Sungai Muda, Kuala Darak  PT4815 & PT4816'],
            ['', 'Permohonan tanah di Kompartmen 3, 4 & 5 Hutan Simpan Relau, Daerah Bandar  Bahar'],
            ['', 'Pelarasan peruntukan pendahuluan diri dibawah PMBKED'],
            ['', 'Bayaran tuntutan bagi membekal backdrop untuk Himpunan Rakan MB.'],
            ['', 'bayaran pembelian toner'],
            ['', 'SALARY 03/2012'],
            ['', 'ALLOWANCES 03/2012'],
            ['', 'FIXED RENTAL & SERVICE 02/2012'],
            ['', 'Bayaran Pendahuluan Perbelanjaan Pengurusan Syarikat Agenda Sejahtera SB.'],
            ['', 'Elaun Setiausaha 03/2012'],
            ['', 'Bayaran  lebihan premium 6 hektar bagi sebahagian Komp. 50, H.S.Pedu '],
            ['', 'Merekacipta,Mencetak dari membekal Kalender Thai 2012, Banner & Backdrop'],
            ['', 'Installment KCL 6608'],
            ['', 'BUKU LAPORAN PERBANDINGAN GAJI SEMASA FAEDAH DAN GANJARAN PEKERJA KILANG'],
            ['', 'BAYARAN MAKANAN DAN MINUMAN UNTUK MESYUARAT'],
            ['', 'Sumbangan Sambutan Jubli Perak Muassasah Darul Ulum 2012'],
            ['', 'Bayaran untuk foto bersama YAB Menteri Besar Kedah sempena Hari Raya di  Mentalo'],
            ['', 'BAYARAN MEMBANGUNKAN HALAMAN SESAWANG KORPORAT '],
            ['', 'PEMBELIAN SERVER'],
            ['', 'Pembelian 1 unit Notebook (Acer Aspire V5-471G Notebook)'],
            ['', 'Car Installment -KBY 11'],
            ['', 'Income Tax 03/2012 - Dato\' Shahabudin'],
            ['', 'Tabung Haji 03/2012 - Zakaria Osman'],
            ['', 'Income Tax 03/2012 - Hj Mihat'],
            ['', 'Tabung Haji 03/2012 - Hana Bt Zakaria'],
            ['', 'Income Tax 03/2012 - Zakaria Osman'],
            ['', 'Bayaran Bil Telefon bagi Bulan 3/2012'],
            ['', 'BONUS BAGI TAHUN 2011'],
            ['', 'Bayaran bagi membekal dan pemasangan Billboard Penerangan Kerajaan Negeri Kedah'],
            ['', 'Sebahagian perbelanjaan pembangunan Projek Mahang untuk tanaman kelapa sawit'],
            ['', 'Bayaran Ganti Notis Eksekutif Perundangan'],
            ['', 'Tuntutan Elaun Harian Wan Zainah Hassan'],
            ['', 'Bayaran guaman untuk kes Bongsu Jaya'],
            ['', 'Bayaran Kos Pemindahan Telefon'],
            ['', 'Tuntutan Elaun Lebih Masa Wan Zainah'],
            ['', 'Sumbangan untuk pasukan futsal kebangsaan ke Kejohanan Futsal di  Bangkok'],
            ['', 'Bayaran permohonan lesen kuari batu granit di Bukit Perak, Pendang'],
            ['', 'Bayaran untuk Kursus inspin (En Asri dan Hj Yaakob - KAHB)'],
            ['', 'Tuntutan Elaun Lebih Masa Mohd Hidzir bagi Bulan April 2012'],
            ['', 'KUMPULAN WANG SIMPANAN PEKERJA'],
            ['', 'Caruman KWSP 04/2012 (Mac)'],
            ['', 'Caruman KWSP 04/2012 (Bonus)'],
            ['', 'Pendahuluan Diri Ke Kuala Lumpur  - Wan Zainah Hassan'],
            ['', 'Bayaran SOCSO Bulan Mac 2012'],
            ['', 'Sumbangan untuk Kejohanan Cabaran Tomoi Dunia Langkawi - Piala DiRaja Kedah'],
            ['', 'FIXED RENTAL / SERVICE ( For Period: 01/07/2012-30/07/2012)'],
            ['', 'FIXED RENTAL & SERVICE 03/2012 (SVAS0010955 & SVAS0010954)'],
            ['', 'Bayaran Bil Internet 04/2012 (20090420368810)'],
            ['', 'Bayaran Bil Internet (20090420368810)'],
            ['', 'Bayaran SmartPay 03/2012'],
            ['', 'Bayaran Jamuan untuk Majlis Jemaah Dato\'-Dato\' Negeri Kedah'],
            ['', 'Bayaran membekal dan mencetak siaran iklan ucapan pertabalan KDYMM  '],
            ['', 'Bayaran Bil Telefon (03/2012 - 7302137)'],
            ['', 'Bayaran untuk signboard dan banner Bukit Kachi (90, 180, 152, 1771 dan 1805)'],
            ['', 'Bayaran lesen menduduki sementara PT2417 Mukim Malau, Tiang Layar'],
            ['', 'Bayaran lesen menduduki sementara PT1128 Tiang Layar Mukim Wang Tepus'],
            ['', 'Bayaran Surat Khabar (Julai 2011 - Mac 2012) '],
            ['', 'Bayaran Bil Perubatan Wan Zainah Hassan'],
            ['', 'PENDAHULUAN DIRI UNTUK MAJLIS JEMAAH DATO-DATO (4  HARI 3 MALAM)'],
            ['', 'Sumbangan untuk Majlis Idul Ilmi Maktab Mahmud Pokok Sena Tahun 2012 '],
            ['', 'Bayaran kuih-muih sempena sambutan hari lahir kakitangan'],
            ['', 'Potongan Tabung Haji Kakitangan'],
            ['', 'Bayaran sambutan hari lahir kakitangan (Nasi & Lauk)'],
            ['', 'Bayaran Elaun Tambahan Kepada Kakitangan Urusetia Penerangan 06/2012'],
            ['', 'PEMBELIAN  PERISIAN UNTUK SERVER'],
            ['', 'BAYARAN PEMBELIAN SISTEM PERAKAUNAN (UBS)'],
            ['', 'YURAN PENYERTAAN KURSUS  (\"APPLYING THE BIG IDEAS OF BLUE OCEAN STRATEGY\"'],
            ['', 'BAYARAN ELAUN KEPADA PEMBANTU KHAS YAB MENTERI BESAR'],
            ['', 'Bayaran Pendahuluan bagi Projek Pemprosesan Nanas.'],
            ['', 'Bayaran saguhati kepada Peserta-peserta Ladang Sejahtera di Pendang'],
            ['', 'Pendahuluan diri untuk Majlis Ladang Sejahtera Langkawi & Sik'],
            ['', 'Bayaran Pembeli Olympus TG 610'],
            ['', 'Pembelian Camera Olympus TG 610'],
            ['', 'Pembelian Camera Olympus TG610'],
            ['', 'Elaun Perjalanan Kenderaan'],
            ['', 'Tuntutan Tambang Pengangkutan Awam'],
            ['', 'Elaun Makan/ Elaun Harian'],
            ['', 'Tuntutan Pelbagai'],
            ['', 'Tuntutan Elaun Kerja Lebih Masa bagi Bulan April 2012'],
            ['', 'BAYARAN BAGI KERJA-KERJA PEMBANGUNAN LDG RAKYAT  PADANG RAGUT,MKM MAHANG(42.5HA)'],
            ['', 'Bayaran SOCSO 04/2012'],
            ['', 'Caruman KWSP 05/2012'],
            ['', 'Tuntutan Elaun lebih Masa Bulan April 2012 (Wan Zainah Hassan)'],
            ['', 'Petrol- Lawatan ke Pantai Remis bersama Y.Bhg Dato\' CEO'],
            ['', 'Haji Mihat Bin Shaari'],
            ['', 'Dato\' Shahabudin Bin Shafie'],
            ['', ' Zakaria Bin Othman'],
            ['', 'Peruntukan Pendahuluan Diri'],
            ['', 'Elaun Setiausaha 07/2012'],
            ['', 'Bayaran SmartPay 04/2012'],
            ['', 'Bayaran mencetak dan membekal Flyers Kedah Sejahtera sebanyak 50,000 keping'],
            ['', 'Tuntutan bayaran daripada Angkatan Edaran Enterprise Sdn Bhd (PMB)'],
            ['', 'Ansuran bulanan (KBY 11) '],
            ['', 'Bayaran saguhati kepada 503 peserta Ladang Sejahtera Daerah Sik'],
            ['', 'Bayaran permohonan tanah bagi PT1591 (Komp. 45 & 46) Plot 1 dan 2, H.S. Bukit Pe'],
            ['', 'Streamer 3\'x6\' dan pemasangan'],
            ['', 'Banner Program 15\'x4\' dan pemasangan'],
            ['', 'Brochure'],
            ['', 'Penunjuk arah ke program'],
            ['', 'Upah pemasangan backdrop - kayu 2\"x1\"x20\"'],
            ['', 'Konsep Design'],
            ['', 'Acer Aspire AS4752 Notebook '],
            ['', 'Sumbangan membeli karpet solat untuk Madrasah As Sibyan.'],
            ['', 'Bayaran Bil Internet 05/2012 (20090420368810)'],
            ['', 'Bayaran Caj untuk Penggunaan Server'],
            ['', 'Bayaran Fixed Rental  & Service (A0ED042007821)  05/2012'],
            ['', 'Saguhati kepada Peserta Ladang Sejahtera Daerah Langkawi'],
            ['', 'Bayaran pembelian baju korporat untuk majlis rasmi (wanita)'],
            ['', 'Peruntukan pakaian korporat (wanita)'],
            ['', 'Bayaran penginapan Tuan Haji Kamarulzaman (Holiday Villa)'],
            ['', 'Makan di Holiday Villa - Haji Kamarulzaman (Manma)'],
            ['', 'Bayaran Bil Telefon 05/2012 (04-730 2137)'],
            ['', 'Bayaran pembelian Bush Jaket'],
            ['', 'Sumbangan Dana Khas untuk keluarga dhaif'],
            ['', 'Pendahuluan tunai untuk kursus di Pahlawan Lake Resort'],
            ['', 'Pendahuluan diri ke K.Lumpur (24hb-26hb Mei 2012)'],
            ['', 'Bayaran pengangkutan di Langkawi (26hb-28hb Mei 2012)'],
            ['', 'Superior Room @ RM160 x 6 Rooms x 1 night'],
            ['', 'Deluxe Room @ RM190 x 2 Rooms x 1 night'],
            ['', 'Bayaran Penginapan di Langkawi (26hb-28hb Mei 2012)'],
            ['', 'Bayaran Elaun Urusetia Penerangan Kerajaan Negeri bagi bulan  5/2012 '],
            ['', 'Pendahuluan diri ke K.Lumpur  bagi Mohd Hidzir B Mohd Zainol (31.05.12-02.06.12)'],
            ['', 'Ustaz Zakaria Bin Othman'],
            ['', 'Zamri Bin Yusuf'],
            ['', 'Bayaran potongan Tabung Haji bagi bulan Mei/2012'],
            ['', 'Pendahuluan Diri Majlis Penyerahan Saguhati Sik'],
            ['', 'Bayaran caruman bagi bulan 05/2012'],
            ['', 'Bayaran caruman bagi bulan 06/2012'],
            ['', 'Bayaran caruman bagi bulan 06/2012'],
            ['', 'Bayaran perkhidmatan penyelenggaraan kereta Toyota (KDC 9900)'],
            ['', 'Bayaran \'Legal Due Diligence Report\''],
            ['', 'PENDAHULUAN PERBELANJAAN MENGURUS KOLEJ UNIVERSITI INSANIAH'],
            ['', 'Pendahuluan gaji Agenda Sejahtera Sdn Bhd  bagi bulan Mei 2012'],
            ['', 'Bayaran Banner & Kad jemputan bagu Majlis Pecah Tanah Batu Quartz'],
            ['', 'Bayaran Elaun Khas kepada Pembantu Khas YAB Menteri Besar bagi bulan 07/2012'],
            ['', 'Bayaran pendahuluan diri ke K.Lumpur untuk 3 hari 2 Malam ( Mohd  Hidzir )'],
            ['', 'Streamer Program 3\'x6\' dan pemasangan'],
            ['', 'Backdrop 20\'x16\' dan pemasangan'],
            ['', 'Kad jemputan dan sampul'],
            ['', 'Brochure'],
            ['', 'Bayaran bagi mengurus program himpunan pemimpim masyarakt bersama YAB MB'],
            ['', 'Sumbangan kewangan bagi menerbitkan Majalah Jelapang'],
            ['', 'Penyediaan mknn petugas, sarapan & makan tghari Ldg Sejhtera Sik'],
            ['', 'Kad Nama (11 Nama x 300 Pcs)'],
            ['', 'Memo Paid'],
            ['', 'Stick Note'],
            ['', 'Bayaran Pengunaan Server'],
            ['', 'Bayaran Caj perkhidmatan Internet 06/2012'],
            ['', 'Tuntutan bayaran sempena Program Kursus Profesional anjuran INSPIN'],
            ['', 'Tuntutan bayaran Elaun lebih masa'],
            ['', 'Tuntutan perjalanan dalam negeri ( Program Ladang Rakyat daerah Langkawi)'],
            ['', 'Mizal Enterprise'],
            ['', 'Majlis Ladang Sejahtera Sik streamer,banner,backdrop,kad jemputan, brochure'],
            ['', 'Bayaran permohonan tanah kerajaan Plot 8, Bagan Samak, Bandar Baharu'],
            ['', 'Peralatan Tulis'],
            ['', 'Bayaran Pendahuluan untuk belanja Pentadbiran '],
            ['', 'Bayaran Bil telefon 06/2012 (04-7302137)'],
            ['', 'BAYARAN UNTUK NANAS SEBAGAI CENDERAHATI KEPADA TETAMU'],
            ['', 'BAYARAN BAGI JAMUAN SEMPENA LAWATAN TUNKU ANNUAR KE BUKIT TANGGA'],
            ['', 'BAYARAN PERBELANJAAN TUNAI SEMPENA LAWATAN TUNKU BENDAHARA'],
            ['', 'BAYARAN PERALATAN SEMPENA LAWATAN TUNKU BENDAHARA KE BUKIT TANGGA'],
            ['', 'Bayaran yuran guaman utk menfailkan notis rayuan yg melibatkan KAIMB'],
            ['', 'installment for KCL6608'],
            ['', 'Bayaran makanan sempena majlis ladang sejahtera di Langkawi(2 ekor Lembu)'],
            ['', 'Bayaran Gratuiti untuk Ketua Pegawai Kewangan PMBKed'],
            ['', 'Bayaran bagi pelarasan pendahuluan diri di bawah PMB(KED)'],
            ['', 'Mohd Farzlis Bin Mohd Noor'],
            ['', 'Noorul Husna Binti Harun'],
            ['', 'Nurul Awanis Binti Md Noh'],
            ['', 'Wan Zainah Binti Hassan'],
            ['', 'Nor Armiza Binti Mokhtar'],
            ['', 'Bayaran tuntutan elaun lebih masa '],
            ['', 'Bayaran caruman KWSP bagi bulan 07/2012'],
            ['', 'Bayaran caruman bagi bulan 06/2012'],
            ['', 'Bayaran pembelian Lembu Feelot dan upah sembelih'],
            ['', 'Bayaran sewa hotel / Elaun Lojing'],
            ['', 'Jamuan Hari LAhir kakitangan (Hj. Mihat, Hidzir, Aishah)'],
            ['', 'Elaun Perjalanan Encik Zulkifle Bin Mohamed'],
            ['', 'Permohonan perlombongan bijjih besi lot 886, Semeling, Kuala Muda'],
            ['', 'Permohonan permit pasir sungai muda kg Sisik Lantai, Mk Tawar, Daerah Baling'],
            ['', 'Bayaran untuk projek pembungkusan ikan keli'],
            ['', 'Bayaran baki bagi pengambilalihan kseluruhan saham dan Kpentingn  di dalam PUHSB'],
            ['', 'Bayaran bagi pemgambilalihan aset & pelatan PUHSB utk AGSB'],
            ['', 'Bayaran elaun lebih masa bagi bulan Jun 2012 (Mohd Hidzir Bin Mohd Zainol)'],
            ['', 'Pembayaran Gaji dan Elaun tanggung tugas Gred N41 ke N48'],
            ['', 'Bayaran tunggakan gaji dan elaun dari Gred N41 ke N48 bagi bulan Feb 12-Jun 12'],
            ['', 'Ansuran Bulanan Kereta (KCL 6608)'],
            ['', 'BAYARAN BG MEMBEKAL BENIH CANTUMAN(BCMP) -GETAH BALAK'],
            ['', 'BAYARAN BG KERJA PEMBANGUNAN LDG HUTAN TANI GNG INS, KOMP 8,BLOK 2, FASA 1'],
            ['', 'Permohonan permit pengambilan pasir sungai Muda, Titi Panjang, Baling'],
            ['', 'Sage Cover renewal for UBS Payroll System (S44000007065)'],
            ['', 'peruntukan pakain petugas wanita  sempena majlis jamuan aidilfitri'],
            ['', 'Proses perlombongan b. besi lot 1295, mk semeling, kuala muda'],
            ['', 'Proses perlombongan b.timah Komp. 4, 5 & 6, G. Bongsu, Kulim'],
            ['', 'Proses permohonan b. besi, sebahagian Komp. 3 & 4, Rimba Teloi'],
            ['', 'Bayaran proses permohonan b.besi lot 1021 dan 1126, Semeling'],
            ['', 'Bayaran proses permohonan tanah lot 9459 Bandar Alor Setar sbg aset PMBKed'],
            ['', 'Bayaran Jamuan Makan bagi Majlis membaca Yassin'],
            ['', 'Keretapi/ Sewa Bot'],
            ['', 'Feri'],
            ['', 'Tol/ Diesel'],
            ['', 'Bayaran tempahan makanan untuk Mensyuarat'],
            ['', 'Combos Value Support Pack'],
            ['', 'Bayaran bagi kerja pembangunan tanah Padang Ragut Mukim Mahang'],
            ['', 'BAYARAN TUNTUTAN BG KERJA PEMBANGUNAN LDG HUTAN TANI BKT KACHI (100HA PERTAMA)'],
            ['', 'Bayaran pendahuluan bagi perbelanjaan Pentadbiran KUIN'],
            ['', 'SUMBANGAN HARI RAYA KEPADA AHLI LEMBAGA PENGARAH SERTA ANAK-ANAK SYARIKAT'],
            ['', 'Bayaran proses permohonan pengambilan pasir sungai, kubang kesom, daerah sik'],
            ['', 'Bayaran penyediaan pelan permohonan tanah di Bukit Kachi, Daerah Kubang Pasu'],
            ['', 'Kerja-kerja ukur bagi cadangan jalan ladang rakyat ke Bukit Kachi'],
            ['', 'Bayaran sumbangan sempena majlis berbuka puasa di Mentaloon pada 1 Ogs 2012'],
            ['', 'Proses permohonan tanah di Bukit Meriam, Daerah Kuala Muda Projek Ternakan Udang'],
            ['', 'Tuntutan bayaran nilaian tanah untuk jalan keluar masuk ke Ladang Bukit Tangga'],
            ['', 'Bayaran Cenderahati dan khemah tambahan semasa Majlis Ladang Sejahtera Sik'],
            ['', 'Pembelian GPS Montana 650'],
            ['', 'Saguhati Raya'],
            ['', 'Saguhati Raya 2012'],
            ['', 'Zakaria Bin Othman '],
        ];
        for($i=0;$i<count($arr);$i++){Item::create([
            'short'=>$arr[$i][0],
            'name'=>$arr[$i][1],
        ]);}
    }
}
