<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
            ['', 'Kedah Communication & Events Sdn. Bhd.', '', '', '', '', ''],
            ['', 'Pejabat Tanah Langkawi', '', '', '', '', ''],
            ['', 'Kedah Corporation Berhad', '', '', '', '', ''],
            ['walking', 'Novel Ventures Sdn. Bhd.', '', '', '', '', ''],
            ['', 'Intersurvey Consultant', '', '', '', '', ''],
            ['', 'Pejabat Tanah Kulim', '', '', '', '', ''],
            ['', 'Kedah Agro CashCrop', '', '', '', '', ''],
            ['', 'Juruukur Aras', '', '', '', '', ''],
            ['', 'Bendahari Negeri Kedah', '', '', '', '', ''],
            ['', 'Pejabat Tanah Sik', '', '', '', '', ''],
            ['', 'Pengarah Perhutanan Negeri Kedah', '', '', '', '', ''],
            ['', 'Pembinaan Sintok Sdn. Bhd.', '', '', '', '', ''],
            ['', 'T.P.K. Star Trading', '', '', '', '', ''],
            ['', 'Agenda Sejahtera Sdn. Bhd.', '', '', '', '', ''],
            ['', 'ZBH Utara Enterprise', '', '', '', '', ''],
            ['', 'Seri Temin Development Corporation (M) Sdn. Bhd.', '', '', '', '', ''],
            ['', 'KEDAH AGRO HOLDINGS BERHAD', '', '', '', '', ''],
            ['', 'PDC Automobile', '', '', '', '', ''],
            ['', 'Rima Jaya Enterprise', '', '', '', '', ''],
            ['PTKM', 'Pentadbir Tanah Kuala Muda', '', '', '', '', ''],
            ['', 'Electrosoft Engineering', '', '', '', '', ''],
            ['', 'MSR GRAFIK', '', '', '', '', ''],
            ['', 'Kedah Agro Aquaculture Sdn Bhd', '', '', '', '', ''],
            ['', 'Satria Purnama Enterprise', '', '', '', '', ''],
            ['', 'KEDAH AGRO INTEGRATED PLANTATIONS SDN BHD', '', '', '', '', ''],
            ['', 'Angkatan Edaran Enterprise Sdn Bhd', '', '', '', '', ''],
            ['', 'SAIF CORPORATION SDN BHD', '', '', '', '', ''],
            ['', 'TETUAN MOHD ANUAR & CO', '', '', '', '', ''],
            ['', 'E & A KOTA SERAYA MANAGEMENT SDN BHD', '', '', '', '', ''],
            ['', 'PAKA UTAMA HOLDINGS SDN BHD', '', '', '', '', ''],
            ['', 'Mohd Anuar & Co.', '', '', '', '', ''],
            ['', 'Malayan Banking Berhad', '', '', '', '', ''],
            ['', 'KK Ang Auto Accessories Sdn. Bhd.', '', '', '', '', ''],
            ['', 'Jabatan Perhutanan Negeri Kedah', '', '', '', '', ''],
            ['', 'RNA Design', '', '', '', '', ''],
            ['', 'Bina Darulaman Berhad', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Kubang Pasu', '', '', '', '', ''],
            ['', 'Tenaga Nasional Berhad', '', '', '', '', ''],
            ['Bayview', 'The City Bayview Hotel Langkawi', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Kulim', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Langkawi', '', '', '', '', ''],
            ['', 'Pengarah Tanah dan Galian Negeri Kedah', '', '', '', '', ''],
            ['', 'Al Farhan Travel & Tours Sdn Bhd', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Sik', '', '', '', '', ''],
            ['', 'Permohonan permit pasir di lot 2208 Padang Temak, Daerah Padang Terap', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Padang Terap', '', '', '', '', ''],
            ['', 'Utas Maju Sdn Bhd', '', '', '', '', ''],
            ['', 'KONICA MINOLTA ', '', '', '', '', ''],
            ['', 'SMARTPAY COLLECT SERVICE', '', '', '', '', ''],
            ['', 'CENASIH MANAGEMENT & SERVICES SDN BHD', '', '', '', '', ''],
            ['', 'TELEKOM MALAYSIA BERHAD', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Bandar Baharu', '', '', '', '', ''],
            ['', 'FINGER TIPS DESIGN,ADVERTISING & MARKETING SDN BHD', '', '', '', '', ''],
            ['', 'mio solution', '', '', '', '', ''],
            ['', 'Kandih Gemilang Enterprise', '', '', '', '', ''],
            ['', 'Rozad Creative Jitra', '', '', '', '', ''],
            ['', 'Maybank Islamic Berhad', '', '', '', '', ''],
            ['', 'FEDERATION OF MALAYSIAN MANUFACTURES', '', '', '', '', ''],
            ['', 'PADIMAZ PRINTING', '', '', '', '', ''],
            ['', 'BFS MANAGEMENT CONSULTANTS SDN BHD', '', '', '', '', ''],
            ['', 'Dana Muassasah Darul Ulum', '', '', '', '', ''],
            ['', 'JOI FOTO STUDIO COLOUR LAB', '', '', '', '', ''],
            ['', 'SUEFI ENTERPRISE', '', '', '', '', ''],
            ['', 'Mecacom Technologies Sdn Bhd', '', '', '', '', ''],
            ['', 'KETUA PENGARAH HASIL DALAM NEGERI', '', '', '', '', ''],
            ['', 'LEMBAGA TABUNG HAJI', '', '', '', '', ''],
            ['', 'Khalek Awang & Associates', '', '', '', '', ''],
            ['', 'Bahrain - Firms Account', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Pendang', '', '', '', '', ''],
            ['', 'Kedah Institute of Management Sdn Bhd', '', '', '', '', ''],
            ['', 'KUMPULAN WANG SIMPANAN PEKERJA', '', '', '', '', ''],
            ['', 'Pertubuhan Keselamatan Sosial - Mac 2012 (SOCSO)', '', '', '', '', ''],
            ['', 'PERTUBUHAN KESELAMATAN SOSIAL', '', '', '', '', ''],
            ['', 'Sinar Karangkraf Sdn Bhd', '', '', '', '', ''],
            ['', 'KEDAH MEDICAL CENTRE SDN. BHD', '', '', '', '', ''],
            ['', 'Pengetua Maktab Mahmud Pokok Sena', '', '', '', '', ''],
            ['', 'ZAIDATY AZIRA MOHD ZAINOL', '', '', '', '', ''],
            ['', 'CSOS COMPUTER SYSTEM', '', '04-323 3670', '019-4473144', '04-323 3670', 'NO.3 LINTANG MAK MANDIN 3,\r\nTAMAN BAYU MAK MANDIN,\r\n13400 BUTTERWORTH\r\nPENANG.'],
            ['', 'KAZTURI IT SOLUTIONS', '', '', '04-732 5996', '04-7332476', '24 TAMAN PELANGI,\r\nJALAN GANGSA, MERGONG\r\n05150 ALOR SETAR\r\nKEDAH'],
            ['', 'INSTITUT PENGURUSAN DAN INTEGRITI NEGERI KEDAH DARUL AMAN (INSPIN)', '', '04-720 3708', '', '', 'NO.321 KOMPLEKS INSPIN\r\nLEBUHRAYA SULTANAH BAHIYAH\r\n05350 ALOR SETAR\r\nKEDAH'],
            ['', 'CIK NURUL\' AIN BINTI BAKHORI', '', '', '', '', ''],
            ['', 'KAKITANGAN URUSETIA PENERANGAN ', '', '', '', '', ''],
            ['', 'Tetuan Madrasah al-Sibyan Kubang Rotan ', '', '', '', '', ''],
            ['', 'Mee Ca Mee Silk Store', '', '', '', '', 'Lot CP 02-49-02-57 City Plaza\r\nJalan Tunku Ibrahim\r\nAlor  Setar'],
            ['', 'Smart Tailor', '', '', '04-730 9661', '', '103 Jalan Langgar\r\n05460 Alor Setar\r\nKedah'],
            ['', 'Persatuan Isteri-isteri wakil rakyat Negeri Kedah', '', '', '', '', ''],
            ['', 'Noorul Husna Binti Harun', '', '', '', '', ''],
            ['', 'My Hotel Management', '', '', '', '', ''],
            ['', 'Lembaga Hasil Dalam Negeri', '', '', '', '', ''],
            ['', 'UMW Toyota Motor Sdn Bhd', '', '', '04-733 8066', '04-735 5440', 'No. 222, Jalan Gangsa\r\n05150 Alor Setar\r\nkedah'],
            ['', 'Rosidi Mustafa & Harryzan', '', '', '', '', 'No.C-2-6 Sunway Business Park\r\nJalan Todak 4,\r\nPusat Bandar Seberang Jaya,\r\n13700 Perai\r\nPulau Pinang'],
            ['', 'Kental Utara Enterprise', '', '', '', '', ''],
            ['', 'Yaacob Bin Awang Ahmad', '', '', '', '', ''],
            ['', 'Mohamad Asri Bin Pazil', '', '', '', '', ''],
            ['', 'Nurul Awanis Binti Md Noh', '', '', '', '', ''],
            ['', 'Nur Aisyah Afzan Binti Bakri', '', '', '', '', ''],
            ['', 'Nor Armiza Binti Mokhtar', '', '', '', '', ''],
            ['', 'Mohd Lukman Bin Haji Mat Isa', '', '', '', '', ''],
            ['', 'Bayaran untuk cenderahati sirap rambutan bagi majlis ladang sejahtera sik', '', '', '', '', ''],
            ['', 'KEDAH AGRO CASHCROP SDN BHD', '', '', '', '', ''],
            ['', 'FIKRAH BAKTI ENTERPRISE', '', '', '', '', ''],
            ['', 'Shamsudin Bahari & Rafidi', '', '', '', '', ''],
            ['', 'Zubir bin Ahmad', '', '', '', '', ''],
            ['', 'Perbadanan Tabung Pendidikan Tinggi Nasional', '', '', '', '', ''],
            ['', 'Laka Temin Silaj Sdn Bhd', '', '', '', '', ''],
            ['', 'Zulkifle Bin Mohamed', '', '', '', '', ''],
            ['', 'Najmuddin Tangga Utara Enterprise', '', '', '', '', ''],
            ['', 'Sekolah Rendah Islam Raudhatul Jannah', '', '', '', '', ''],
            ['', 'FH UTARA AUTO', '', '', '', '', ''],
            ['', 'Yayasan Sultanah Bahiyah', '', '', '', '', ''],
            ['', 'E&A KOTA SERAYA MANAGEMENT SDN BHD', '', '', '', '', ''],
            ['', 'BAMBOO HILL ENTERPRISE', '', '', '', '', ''],
            ['', 'LIMAN PLANTATIONS SDN BHD', '', '', '', '', ''],
            ['', 'Pentadbir Tanah Daerah Kota Setar', '', '', '', '', ''],
            ['', 'Perniagaan Mazlan & Hashimah', '', '', '04-7722035', '', 'Lot 1287B Jalan Tunku Abdul Rahman\r\nLencong Barat\r\n05050 Alor Setar\r\nKedah'],
            ['', 'NSR MAJU ENGINEERING & SUPPLIES SDN BHD', '', '', '', '', ''],
            ['', 'Haifa Bina Sdn Bhd', '', '', '', '', ''],
            ['', 'SLCS GOH SDN BHD', '', '', '', '', ''],
            ['', 'ANGKASA', '', '', '', '', 'Wisma Ungku A.Aziz Peti Surat 8797, \r\nPejabat Pos Kelana Jaya,\r\n46798 Petaling Jaya,\r\nSelangor'],
            ['', 'Dewan Perniagaan Melayu Malaysia Negeri Kedah', '', '', '', '', 'Tingkat 4, Bangunan DPMK,\r\nPeti Surat 59, \r\nJalan Tunku Ibrahim, \r\n05700 Alor Setar,\r\nKedah'],
            ['', 'Majlis Perwakilan Mahasiswa KUIN', '', '', '', '', ''],
            ['', 'SUMBANGAN HARI RAYA KEPADA AHLI LEMBAGA PENGARAH SERTA ANAK-ANAK SYARIKAT', '', '', '', '', ''],
            ['', 'seperti dalam lampiran', '', '', '', '', ''],
            ['', 'Ahli-Ahli Badan Penasihat PMBKed', '', '', '', '', ''],
            ['', 'Pusat Khidmat Wakil Rakyat Adun Kubang Rotan', '', '', '', '', ''],
            ['', 'Puncak Selera Sdn Bhd', '', '', '', '', ''],
            ['', 'Syarikat Jurukur Konsultant', '', '', '', '', ''],
            ['', 'Alor Setar Holiday Villa Sdn Bhd', '', '', '', '', 'Holiday Villa City Centre Alor Setar'],
            ['', 'Mohd Fahmi Bin Ishak', '', '', '', '', ''],
            ['', 'Starcare', '', '', '', '', ''],
            ['', 'STAR PRIMA CORPORATION SDN BHD', '', '', '', '', ''],
            ['', 'Tan Chin Hock', '', '', '', '', ''],
            ['', 'Akauntan Negara Malaysia', '', '', '', '', ''],
            ['', 'Ahmad Zuhairi Bin Zubit', '', '', '', '', ''],
            ['', 'Hong Leong Bank Berhad', '', '', '', '', ''],
            ['', 'Unit Hesa', '', '', '', '', ''],
            ['', 'Praiman Sdn Bhd', '', '', '', '', 'No.2497A, Jalan Pekan Pumpong\r\n05250 Alor Setar \r\nKedah'],
            ['', 'Shathirah binti Rabian', '', '', '', '', ''],
            ['', 'Pentabdir Tanah Sik', '', '', '', '', ''],
            ['', 'MMG Technology Sdn Bhd', '', '', '', '', ''],
            ['', 'Pegawai Daerah Sik', '', '', '', '', ''],
            ['', 'Syarikat Kejuruteraan Antara', '', '', '', '', ''],
            ['', 'Photobiz Centre', '', '', '', '', ''],
            ['', 'Ban hoo Electrical & Furniture (Kedah) Sdn Bhd', '', '', '', '', ''],
            ['', 'RYVERRA CHOCOLATEN & CONFECTIONERY SDN BHD', '', '', '', '', ''],
            ['', 'Infografik Design Consultants', '', '', '', '', ''],
            ['', 'Seri Panglima Sdn Bhd', '', '', '', '', ''],
            ['', 'PENSO SUN ENTERPRISE', '', '', '', '', ''],
            ['', 'Anjung Kuala Enterprise', '', '', '', '', ''],
            ['', 'Noor Hidayah Binti Othman', '', '', '', '', ''],
            ['', 'LEMBAGA BIASISWA NEGERI KEDAH', '', '', '', '', ''],
            ['', 'Restoran Tepi Sungai', '', '', '', '', ''],
            ['', 'Chin Hin (Mergong) Sdn Bhd', '', '', '', '', ''],
            ['', 'RA NETWORK SERVICES', '', '', '', '', ''],
            ['', 'Mohammad Fuad Bin Ismail', '', '', '', '', ''],
            ['', 'Majlis Perwakilan Mahasiswa (MPM)', '', '', '', '', ''],
            ['', 'ALYASAK BIN JAMEL', '', '', '', '', ''],
            ['', 'Twin Speed Auto Services', '', '', '', '', ''],
            ['', 'Storeyard Enterprise', '', '', '', '', ''],
            ['', 'Yuscom Technology Sdn Bhd', '', '', '', '', ''],
            ['', 'Erna Binti Mahmud', '', '', '', '', ''],
            ['', 'Abdul Nasir Bin Khamis @ Man', '', '', '', '', ''],
            ['', 'Bendahari UTM', '', '', '', '', ''],
            ['', 'Majlis Sukan Negeri Kedah', '', '', '', '', ''],
            ['', 'Razihan Holidays Sdn Bhd', '', '', '', '', ''],
        ];
        for($i=0;$i<count($arr);$i++){Supplier::create([
            'short'=>$arr[$i][0],
            'name'=>$arr[$i][1],
            'attn'=>$arr[$i][2],
            'hp'=>$arr[$i][3],
            'tel'=>$arr[$i][4],
            'fax'=>$arr[$i][5],
            'addr'=>$arr[$i][6]
        ]);}
    }
}
