<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BillingRecipientSeeder extends Seeder
{
    public function run()
    {
        $billing_recipients = [
            ['short' => '', 'name' => 'Kedah Communication & Events Sdn. Bhd.', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pejabat Tanah Langkawi', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Kedah Corporation Berhad', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => 'walking', 'name' => 'Novel Ventures Sdn. Bhd.', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Intersurvey Consultant', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pejabat Tanah Kulim', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Kedah Agro CashCrop', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Juruukur Aras', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Bendahari Negeri Kedah', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pejabat Tanah Sik', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pengarah Perhutanan Negeri Kedah', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pembinaan Sintok Sdn. Bhd.', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'T.P.K. Star Trading', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Agenda Sejahtera Sdn. Bhd.', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'ZBH Utara Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Seri Temin Development Corporation (M) Sdn. Bhd.', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'KEDAH AGRO HOLDINGS BERHAD', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'PDC Automobile', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Rima Jaya Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => 'PTKM', 'name' => 'Pentadbir Tanah Kuala Muda', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Electrosoft Engineering', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'MSR GRAFIK', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Kedah Agro Aquaculture Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Satria Purnama Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'KEDAH AGRO INTEGRATED PLANTATIONS SDN BHD', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Golden Harvest Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Maju Jaya Sdn. Bhd.', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Zamrud Construction', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Top Builders Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Jaya Murni Services', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Lestari Engineering', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Aman Jaya Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Cahaya Gemilang Services', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Angkatan Edaran Enterprise Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'SAIF CORPORATION SDN BHD', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Mega Jaya Trading', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Sri Aman Engineering', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Tunas Maju Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Kedah Agro Trading', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Permata Hijau Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Satria Purnama Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Kedah Agro CashCrop Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Bina Darulaman Berhad', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Tenaga Nasional Berhad', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Malayan Banking Berhad', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Lembaga Tabung Haji', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Kumpulan Wang Simpanan Pekerja', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Hong Leong Bank Berhad', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Unit Hesa', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Praiman Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => 'No.2497A, Jalan Pekan Pumpong\r\n05250 Alor Setar \r\nKedah'],
            ['short' => '', 'name' => 'Shathirah binti Rabian', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pentadbir Tanah Sik', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'MMG Technology Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pegawai Daerah Sik', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Syarikat Kejuruteraan Antara', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Photobiz Centre', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Ban Hoo Electrical & Furniture (Kedah) Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'RYVERRA CHOCOLATEN & CONFECTIONERY SDN BHD', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Infografik Design Consultants', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Seri Panglima Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'PENSO SUN ENTERPRISE', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Anjung Kuala Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Noor Hidayah Binti Othman', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'LEMBAGA BIASISWA NEGERI KEDAH', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Restoran Tepi Sungai', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Chin Hin (Mergong) Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'RA NETWORK SERVICES', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Mohammad Fuad Bin Ismail', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Majlis Perwakilan Mahasiswa (MPM)', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'ALYASAK BIN JAMEL', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Twin Speed Auto Services', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Storeyard Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Yuscom Technology Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Erna Binti Mahmud', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Abdul Nasir Bin Khamis @ Man', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Bendahari UTM', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Majlis Sukan Negeri Kedah', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Razihan Holidays Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Twin Speed Auto Services', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Storeyard Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Yuscom Technology Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Erna Binti Mahmud', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Majlis Perwakilan Mahasiswa (MPM)', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'ALYASAK BIN JAMEL', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Twin Speed Auto Services', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Storeyard Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Yuscom Technology Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Erna Binti Mahmud', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Abdul Nasir Bin Khamis @ Man', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Bendahari UTM', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Majlis Sukan Negeri Kedah', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Razihan Holidays Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Shathirah binti Rabian', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pentadbir Tanah Sik', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'MMG Technology Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Pegawai Daerah Sik', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Syarikat Kejuruteraan Antara', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Photobiz Centre', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Ban hoo Electrical & Furniture (Kedah) Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'RYVERRA CHOCOLATEN & CONFECTIONERY SDN BHD', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Infografik Design Consultants', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Seri Panglima Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'PENSO SUN ENTERPRISE', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Anjung Kuala Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Noor Hidayah Binti Othman', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'LEMBAGA BIASISWA NEGERI KEDAH', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Restoran Tepi Sungai', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Chin Hin (Mergong) Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'RA NETWORK SERVICES', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Mohammad Fuad Bin Ismail', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Majlis Perwakilan Mahasiswa (MPM)', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'ALYASAK BIN JAMEL', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Twin Speed Auto Services', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Storeyard Enterprise', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Yuscom Technology Sdn Bhd', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Erna Binti Mahmud', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Abdul Nasir Bin Khamis @ Man', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => ''],
            ['short' => '', 'name' => 'Bendahari UTM', 'attn' => '', 'hp' => '', 'tel' => '', 'fax' => '', 'addr' => '']
        ];
        foreach ($billing_recipients as $recipient) {
            DB::table('billing_recipients')->updateOrInsert(
                [
                    'name' => $recipient['name'],
                    'short' => $recipient['short'],
                    'attn' => $recipient['attn'],
                    'hp' => $recipient['hp'],
                    'tel' => $recipient['tel'],
                    'fax' => $recipient['fax'],
                    'addr' => $recipient['addr']
                ] // Values to update or insert
            );
        }
    }
}
